name: drupalnextheadless
recipe: drupal9
config:
  webroot: web
  via: nginx
  php: 8.1
  database: mysql
services:
  database:
    creds:
      user: "admin"
      password: "admin"
      database: "headless"
    arguments:
      [ '@?', '@?' ]
  solr:
    type: solr:8.1
    core: headless-index
    config:
      dir: search/solr/config
  phpmyadmin:
    type: phpmyadmin
proxy:
  solr:
    - admin.solr.lndo.site:8983
